FROM         ubuntu:18.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  curl \
  git \
  tar \
  wget \
  xz-utils \
  libpcap-dev \
  cmake \
  doxygen

# Install Zstd
RUN wget https://github.com/facebook/zstd/releases/download/v1.4.4/zstd-1.4.4.tar.gz
RUN tar xvzf zstd-1.4.4.tar.gz
RUN cd zstd-1.4.4 && make install
RUN echo "/usr/local/lib" >> /etc/ld.so.conf
RUN ldconfig | grep zstd