FROM         ubuntu:20.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash
ARG          DPDK_VERSION="18.11.11"
ARG          DPDK_TARGET="x86_64-native-linuxapp-gcc"

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  cmake \
  curl \
  git \
  libnuma-dev \
  libpcap-dev \
  linux-virtual \
  meson \
  pkg-config \
  python3-pip \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay

# Create link to /lib/modules for this kernel
RUN cd /lib/modules && \
  ln -s *-generic `uname -r`

RUN wget http://fast.dpdk.org/rel/dpdk-${DPDK_VERSION}.tar.gz \
  && tar xvzf dpdk-${DPDK_VERSION}.tar.gz \
  && rm -rf dpdk-${DPDK_VERSION}.tar.gz \
  && mv dpdk-stable-${DPDK_VERSION} dpdk && cd dpdk \
  && meson build && cd build && ninja && ninja install && ldconfig \

# Update python3 pip
RUN python3 -m pip install --upgrade pip setuptools wheel
