FROM         ubuntu:20.04
LABEL        org.opencontainers.image.authors="PcapPlusPlus <pcapplusplus@gmail.com>"
CMD          bash

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  clang-9 \
  cmake \
  curl \
  doxygen \
  git \
  libpcap-dev \
  pkg-config \
  python3-pip \
  software-properties-common \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay

RUN ln -s /usr/bin/clang-9 /usr/bin/clang \
  && ln -s /usr/bin/clang++-9 /usr/bin/clang++

# Update python3 pip
RUN python3 -m pip install --upgrade pip setuptools wheel

# Update CMake to latest version
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - \
  && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' \
  && apt-get update && apt-get install -y cmake