FROM         centos:8
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash

# Required system packages
RUN yum update -y && yum upgrade -y && yum install -y \
  unzip \
  build-essential \
  curl \
  git \
  wget \
  libpcap-devel \
  cmake \
  zlib-devel \
  bzip2-devel \
  libffi-devel \
  openssl-devel

RUN yum group install -y "Development Tools"
RUN yum install -y libstdc++-static

# Install Python 3.8
RUN cd /opt && wget https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz
RUN cd /opt && tar xzf Python-3.8.3.tgz
RUN cd /opt/Python-3.8.3 && ./configure --enable-optimizations && make altinstall
RUN rm -rf /opt/Python-3.8.3.tgz
RUN python3.8 -m pip install --upgrade pip setuptools wheel
RUN python3.8 -m pip install pytest
