FROM         ubuntu:20.04
LABEL        org.opencontainers.image.authors="PcapPlusPlus <pcapplusplus@gmail.com>"
CMD          bash
ARG          DPDK_VERSION="20.11.9"

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  cmake \
  curl \
  git \
  libnuma-dev \
  libpcap-dev \
  meson \
  pkg-config \
  python3-pip \
  software-properties-common \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay

RUN wget http://fast.dpdk.org/rel/dpdk-${DPDK_VERSION}.tar.gz \
  && tar xvzf dpdk-${DPDK_VERSION}.tar.gz \
  && rm -rf dpdk-${DPDK_VERSION}.tar.gz \
  && mv dpdk-stable-${DPDK_VERSION} dpdk && cd dpdk \
  && meson build && cd build && ninja && ninja install && ldconfig

# Update python3 pip
RUN python3 -m pip install --upgrade pip setuptools wheel

# Update CMake to latest version
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - \
  && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' \
  && apt-get update && apt-get install -y cmake
