FROM         centos:7
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash
ARG          PYTHON_VERSION="3.8.16"
ARG          CMAKE_VERSION="3.22.2"
ARG          GIT_VERSION="2.35.1"
ARG          TCPREPLAY_VERSION="4.4.1"

# Required system packages
RUN yum upgrade -y && yum install -y \
  build-essential \
  bzip2-devel \
  curl \
  curl-devel \
  gcc-c++ \
  gettext \
  libffi-devel \
  libpcap-devel \
  libstdc++-static \
  make \
  openssl-devel \
  pkg-config \
  unzip \
  wget \
  zlib-devel \
  net-tools

# Install tcpreplay
RUN cd /opt && wget https://github.com/appneta/tcpreplay/releases/download/v${TCPREPLAY_VERSION}/tcpreplay-${TCPREPLAY_VERSION}.tar.gz \
  && tar xvf tcpreplay-${TCPREPLAY_VERSION}.tar.gz \
  && cd /opt/tcpreplay-${TCPREPLAY_VERSION} && ./configure && make && make install \
  && rm -rf /opt/tcpreplay-${TCPREPLAY_VERSION}.tar.gz /opt/tcpreplay-${TCPREPLAY_VERSION}

# Install Python 3.8
RUN cd /opt && wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
  && tar xzf Python-${PYTHON_VERSION}.tgz \
  && cd /opt/Python-${PYTHON_VERSION} && ./configure --enable-optimizations && make install \
  && rm -rf /opt/Python-${PYTHON_VERSION}.tgz /opt/Python-${PYTHON_VERSION}

RUN python3 -m pip install --upgrade pip setuptools wheel pytest

# Install Recent Cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz \
  && tar xzf cmake-${CMAKE_VERSION}.tar.gz \
  && cd cmake-${CMAKE_VERSION} \
  && ./bootstrap --prefix=/usr/local \
  && make -j$(nproc) && make install \
  && cd .. && rm -rf cmake-${CMAKE_VERSION}*

# Install Recent Git
RUN wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VERSION}.tar.gz \
  && tar xf git-${GIT_VERSION}.tar.gz && rm -rf git-${GIT_VERSION}.tar.gz \
  && cd git-${GIT_VERSION}/ \
  && ./configure --prefix=/usr/local \
  && make -j all && make install \
  && cd .. && rm -rf git-${GIT_VERSION}
