FROM         ubuntu:16.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  curl \
  git \
  tar \
  wget \
  xz-utils \
  libpcap-dev \
  cmake \
  linux-headers-$(uname -r) \
  flex \
  byacc \
  libnuma-dev

RUN git clone https://github.com/ntop/PF_RING.git
RUN cd /PF_RING && git checkout $(git describe --tags --abbrev=0)
RUN cd /PF_RING/kernel && make 
# && insmod ./pf_ring.ko
RUN cd /PF_RING/userland && make
