FROM         ubuntu:20.04
LABEL        org.opencontainers.image.authors="PcapPlusPlus <pcapplusplus@gmail.com>"
CMD          bash
ARG          ZSTD_VERSION="1.5.2"

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  ccache \
  cmake \
  curl \
  doxygen \
  git \
  libpcap-dev \
  pkg-config \
  python3-pip \
  software-properties-common \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay

# Install Zstd
RUN wget https://github.com/facebook/zstd/releases/download/v${ZSTD_VERSION}/zstd-${ZSTD_VERSION}.tar.gz \
  && tar xvzf zstd-${ZSTD_VERSION}.tar.gz \
  && cd zstd-${ZSTD_VERSION} && make install \
  && cd .. && rm -rf zstd-${ZSTD_VERSION} \
  && echo "/usr/local/lib" >> /etc/ld.so.conf

# Update CMake to latest version
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - \
  && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' \
  && apt-get update && apt-get install -y cmake