FROM         ubuntu:16.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash
ARG          PYTHON_VERSION="3.8.12"

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  curl \
  git \
  tar \
  wget \
  xz-utils \
  libpcap-dev \
  cmake \
  software-properties-common \
  net-tools \
  tcpreplay \
  zlib1g-dev \
  ca-certificates

# Install Python 3.8
RUN cd /opt && wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
  && tar xzf Python-${PYTHON_VERSION}.tgz \
  && cd /opt/Python-${PYTHON_VERSION} && ./configure --enable-optimizations && make altinstall \
  && rm -rf /opt/Python-${PYTHON_VERSION}.tgz /opt/Python-${PYTHON_VERSION}

RUN python3.8 -m ensurepip && python3.8 -m pip install --upgrade pip setuptools wheel
RUN python3.8 -m pip install pytest