FROM         ubuntu:20.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  bison \
  build-essential \
  byacc \
  cmake \
  curl \
  flex \
  git \
  libnuma-dev \
  libpcap-dev \
  linux-virtual \
  pkg-config \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay

# Create link to /lib/modules for this kernel
RUN cd /lib/modules && \
  ln -s *-generic `uname -r`

RUN git clone https://github.com/ntop/PF_RING.git \
  && cd /PF_RING && git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) \
  && cd /PF_RING/kernel && make  \
  && cd /PF_RING/userland && make
