FROM         ubuntu:18.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  clang-9 \
  cmake \
  curl \
  doxygen \
  git \
  libpcap-dev \
  software-properties-common \
  tar \
  wget \
  xz-utils

RUN ln -s /usr/bin/clang-9 /usr/bin/clang \
  && ln -s /usr/bin/clang++-9 /usr/bin/clang++

# Install Python 3.8
RUN add-apt-repository -y ppa:deadsnakes/ppa \
  && apt update && apt -y install python3.8 python3.8-venv python3.8-dev \
  && python3.8 -m ensurepip && python3.8 -m pip install --upgrade pip setuptools wheel \
  && python3.8 -m pip install pytest