FROM         fedora:29
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash

# Required system packages
RUN dnf upgrade -y && dnf install -y \
  cmake \
  curl \
  gcc-c++ \
  git \
  libpcap-devel \
  libstdc++-static \
  pkg-config \
  unzip \
  wget \
  && dnf groupinstall -y 'Development Tools'

# Install pytest
RUN python3 -m pip install pytest
