FROM         ubuntu:20.04
LABEL        org.opencontainers.image.authors="PcapPlusPlus <pcapplusplus@gmail.com>"
CMD          bash

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  bison \
  build-essential \
  byacc \
  ccache \
  cmake \
  curl \
  flex \
  git \
  libnuma-dev \
  libpcap-dev \
  linux-virtual \
  pkg-config \
  python3-pip \
  software-properties-common \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay \
  python3-venv \
  python3-dev

# Create link to /lib/modules for this kernel
RUN cd /lib/modules && \
  ln -s *-generic `uname -r`

RUN git clone https://github.com/ntop/PF_RING.git \
  && cd /PF_RING && git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) \
  && cd /PF_RING/kernel && make  \
  && cd /PF_RING/userland && make

# Update python3 pip
RUN python3 -m pip install --upgrade pip setuptools wheel

# Update CMake to latest version
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - \
  && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' \
  && apt-get update && apt-get install -y cmake
