FROM         ubuntu:20.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash
ARG          ZSTD_VERSION="1.5.2"

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  cmake \
  curl \
  doxygen \
  git \
  libpcap-dev \
  tar \
  wget \
  xz-utils

# Install Zstd
RUN wget https://github.com/facebook/zstd/releases/download/v${ZSTD_VERSION}/zstd-${ZSTD_VERSION}.tar.gz \
  && tar xvzf zstd-${ZSTD_VERSION}.tar.gz \
  && cd zstd-${ZSTD_VERSION} && make install \
  && cd .. && rm -rf zstd-${ZSTD_VERSION} \
  && echo "/usr/local/lib" >> /etc/ld.so.conf
