FROM         ubuntu:18.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  clang-9 \
  cmake \
  curl \
  doxygen \
  git \
  libpcap-dev \
  pkg-config \
  software-properties-common \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay

RUN ln -s /usr/bin/clang-9 /usr/bin/clang \
  && ln -s /usr/bin/clang++-9 /usr/bin/clang++

# Install Python 3.8
RUN add-apt-repository -y ppa:deadsnakes/ppa \
  && apt-get update && apt-get -y install python3.8 python3.8-venv python3.8-dev \
  && python3.8 -m ensurepip \
  && python3.8 -m pip install --upgrade pip pytest setuptools wheel \
  && ln -sf /usr/bin/python3.8 /usr/bin/python3

# Update git to latest version
RUN add-apt-repository -y ppa:git-core/ppa \
  && apt-get update && apt-get -y install git

# Update CMake to latest version
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add - \
  && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' \
  && apt-get update && apt-get install -y cmake
