FROM         ubuntu:26.04
LABEL        org.opencontainers.image.authors="PcapPlusPlus <pcapplusplus@gmail.com>"
CMD          bash

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  ccache \
  cmake \
  curl \
  doxygen \
  git \
  libpcap-dev \
  pkg-config \
  python3-pip \
  software-properties-common \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay \
  python3-venv \
  python3-dev \
  libnl-genl-3-dev \
  bison \
  flex

RUN git clone https://github.com/ntop/PF_RING.git \
  && cd /PF_RING && git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) \
  && cd /PF_RING/userland && make
