ARG          FEDORA_VERSION=37
FROM         fedora:${FEDORA_VERSION}
# Recall ARG to have the FEDORA_version in case we need it see:
# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG          FEDORA_VERSION
LABEL org.opencontainers.image.authors="PcapPlusPlus <pcapplusplus@gmail.com>"
CMD          bash

# Install alpine required system packages
ADD scripts/fedora_install.sh /
RUN /fedora_install.sh && rm /fedora_install.sh
