FROM         ubuntu:22.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash
ARG          DPDK_VERSION="22.11.3"

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  cmake \
  curl \
  git \
  libnuma-dev \
  libpcap-dev \
  meson \
  pkg-config \
  python3-pip \
  tar \
  wget \
  xz-utils \
  net-tools \
  tcpreplay

# Update python3 pip
RUN python3 -m pip install --upgrade pip setuptools wheel && pip install pyelftools

RUN wget http://fast.dpdk.org/rel/dpdk-${DPDK_VERSION}.tar.gz \
  && tar xvzf dpdk-${DPDK_VERSION}.tar.gz \
  && rm -rf dpdk-${DPDK_VERSION}.tar.gz \
  && mv dpdk-stable-${DPDK_VERSION} dpdk && cd dpdk \
  && meson build && cd build && ninja && ninja install && ldconfig
