FROM         ubuntu:16.04
MAINTAINER   PcapPlusPlus <pcapplusplus@gmail.com>
CMD          bash

# Required system packages
RUN apt-get update && apt-get -y install \
  apt-utils \
  build-essential \
  curl \
  git \
  tar \
  wget \
  xz-utils \
  libpcap-dev \
  cmake \
  software-properties-common

# Install Python 3.8
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt update && apt -y install python3.8 python3.8-venv python3.8-dev
RUN python3.8 -m ensurepip && python3.8 -m pip install --upgrade pip setuptools wheel
RUN python3.8 -m pip install pytest